const fs=require('fs'), vm=require('vm');
const stageIdx=Number(process.argv[2]||0), startEp=Number(process.argv[3]||0), chunk=Number(process.argv[4]||0), totalOverride=Number(process.argv[5]||0), inModel=process.argv[6]||'', outModel=process.argv[7], outSummary=process.argv[8];
const ids={}; function ctx(){return {clearRect(){},fillRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},arc(){},fill(){},ellipse(){},rect(){},fillText(){},save(){},restore(){},setLineDash(){}};}
function elem(id){if(!ids[id])ids[id]={id,value:'',textContent:'',innerHTML:'',disabled:false,scrollTop:0,scrollHeight:0,width:900,height:430,getContext:ctx};return ids[id];}
const cfgVals={numCranes:3,numLifts:24,craneType:'50톤 모바일 크레인',fixedDuration:25,setupTime:10,craneRadius:18,episodes:150,maxSteps:220,alpha:0.18,gamma:0.92,epsStart:0.35,epsEnd:0.05,seedRuns:10,baseSeed:101,learningMode:'multi',learningAlgorithm:'mappo',actorShareMode:'typeShared',candidateK:5,actorLr:0.001,criticLr:0.002,gaeLambda:0.95,ppoClip:0.20,rSingle:10,rAll:100,rSame:3,pIdle:-0.5,pInterSoft:-3,pInterHard:-15,liftingRadius:8,safetyRadius:14,pTime:-0.1,pMove:-0.02};
for(const [k,v] of Object.entries(cfgVals)) elem(k).value=String(v);
['log','metricLog','interpretLog','baselineRows','repeatRows','agentRows','scheduleLog','mEpisode','mReward','mBest','mDone','mEvalMakespan','mInter','mTravel','mSetup','mMove','trainBtn','sim','rewardChart','metricChart','replaySlider','replayInfo','replaySpeed'].forEach(elem); elem('replaySpeed').value='1';
const context={console,Math,Date,setInterval,clearInterval,document:{getElementById:elem,createElement:()=>({click(){},remove(){}})},body:{appendChild(){}}}; context.Blob=function(){}; context.URL={createObjectURL:()=>'',revokeObjectURL(){}}; context.global=context; vm.createContext(context); vm.runInContext(fs.readFileSync(require('path').join(__dirname,'crane_script.js'),'utf8'),context); vm.runInContext('log=function(){}; drawAll=function(){}; drawSim=function(){}; drawChart=function(){}; updateAll=function(){};',context);
if(inModel && fs.existsSync(inModel)){ const m=JSON.parse(fs.readFileSync(inModel,'utf8')); vm.runInContext('restoreMappoModel('+JSON.stringify(m)+')',context); } else vm.runInContext('initMappoModel()',context);
const code=`(()=>{const st=curriculumStages()[${stageIdx}]; applyStageConfig(st); if(${totalOverride}>0)$('episodes').value='${totalOverride}'; const c=cfg(); const from=${startEp}+1; const to=${chunk}>0?Math.min(c.episodes,${startEp}+${chunk}):c.episodes; const ran=Math.max(0,to-${startEp}); const t0=Date.now(); let stageBest=null, doneSum=0, rewardSum=0, hardSum=0, softSum=0, makeSum=0; const span=Math.max(1,c.seedRuns||1); const globalOffset=${stageIdx===0?0:(stageIdx===1?100:250)}; for(let ep=from; ep<=to; ep++){ const globalEp=globalOffset+ep; const trainSeed=(c.baseSeed||101)+((ep-1)%span); generateScenario(trainSeed,true,true); setSeed(trainSeed*3000+globalEp); const eps=c.epsStart+(c.epsEnd-c.epsStart)*(ep/c.episodes); const r=runEpisode(globalEp,true,eps,'mappo'); doneSum+=r.done/r.total; rewardSum+=r.reward; hardSum+=(r.hardInter||0); softSum+=(r.softInter||0); makeSum+=r.makespan; if(r.done===r.total && (!stageBest || r.makespan<stageBest.makespan)) stageBest=r; } const m=cloneMappoModel(); m.curriculum={...(m.curriculum||{}), totalEpisodes:((m.curriculum&&m.curriculum.totalEpisodes)||0)+ran, chunks:[...((m.curriculum&&m.curriculum.chunks)||[]),{stage:st.name,start:from,end:to,episodes:ran,nC:c.nC,nL:c.nL}]}; return {model:m,summary:{stage:st.name,chunkStart:from,chunkEnd:to,chunkEpisodes:ran,nC:c.nC,nL:c.nL,totalStageEpisodes:c.episodes,seedRuns:c.seedRuns,candidateK:c.candidateK,maxSteps:c.maxSteps,elapsedSec:(Date.now()-t0)/1000,bestMakespan:stageBest?stageBest.makespan:null,avgComplete:100*doneSum/Math.max(1,ran),avgReward:rewardSum/Math.max(1,ran),avgMakespan:makeSum/Math.max(1,ran),avgHardMask:hardSum/Math.max(1,ran),avgSoft:softSum/Math.max(1,ran),updates:m.stats.updates,actorDim:m.stats.actorDim,criticDim:m.stats.criticDim}}})()`;
const res=vm.runInContext(code,context); fs.writeFileSync(outModel,JSON.stringify(res.model)); fs.writeFileSync(outSummary,JSON.stringify(res.summary,null,2)); console.log(JSON.stringify(res.summary,null,2));
